# Generated by Django 3.2.25 on 2024-07-05 13:14

import delft3dworker.models
import delft3dworker.utils
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('scenes_parameters', delft3dworker.models.JSONFieldTransition(blank=True, default=dict)),
                ('parameters', delft3dworker.models.JSONFieldTransition(blank=True, default=dict)),
                ('state', models.CharField(default='CREATED', max_length=64)),
                ('progress', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('suid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(blank=True, default=delft3dworker.utils.tz_now)),
                ('date_started', models.DateTimeField(blank=True, null=True)),
                ('fileurl', models.CharField(max_length=256)),
                ('info', delft3dworker.models.JSONFieldTransition(blank=True, default=dict)),
                ('parameters', delft3dworker.models.JSONFieldTransition(blank=True, default=dict)),
                ('state', models.CharField(default='CREATED', max_length=256)),
                ('progress', models.IntegerField(default=0)),
                ('task_id', models.CharField(blank=True, max_length=256)),
                ('workingdir', models.CharField(max_length=256)),
                ('parameters_hash', models.CharField(blank=True, max_length=64)),
                ('shared', models.CharField(choices=[('p', 'private'), ('c', 'company'), ('w', 'world')], max_length=1)),
                ('phase', models.PositiveSmallIntegerField(choices=[(0, 'New'), (6, 'Idle: waiting for user input'), (11, 'Starting workflow'), (12, 'Running workflow'), (13, 'Removing workflow'), (20, 'Stopping workflow'), (21, 'Removing stopped workflow'), (500, 'Finished'), (501, 'Failed'), (502, 'Stopped')], default=0)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ManyToManyField(blank=True, to='delft3dworker.Scenario')),
            ],
            options={
                'permissions': [('extended_view_scene', 'Can view scene with actions.')],
            },
        ),
        migrations.CreateModel(
            name='SearchForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('templates', delft3dworker.models.JSONFieldTransition(default=list)),
                ('sections', delft3dworker.models.JSONFieldTransition(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('shortname', models.CharField(default=dict, max_length=256)),
                ('meta', delft3dworker.models.JSONFieldTransition(blank=True, default=dict)),
                ('info', delft3dworker.models.JSONFieldTransition(blank=True, default=dict)),
                ('sections', delft3dworker.models.JSONFieldTransition(blank=True, default=dict)),
                ('visualisation', delft3dworker.models.JSONFieldTransition(blank=True, default=dict)),
                ('export_options', delft3dworker.models.JSONFieldTransition(blank=True, default=dict)),
                ('yaml_template', models.FileField(default='', upload_to=delft3dworker.models.parse_argo_workflow)),
            ],
        ),
        migrations.CreateModel(
            name='Version_Docker',
            fields=[
                ('release', models.CharField(db_index=True, max_length=256)),
                ('revision', models.AutoField(primary_key=True, serialize=False)),
                ('versions', delft3dworker.models.JSONFieldTransition(default=dict)),
                ('changelog', models.CharField(max_length=256)),
                ('reviewed', models.BooleanField(default=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='delft3dworker.template')),
            ],
            options={
                'verbose_name': 'Docker version',
                'verbose_name_plural': 'Docker versions',
                'ordering': ['-revision'],
            },
        ),
        migrations.CreateModel(
            name='GroupUsageSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Group Usage Summary',
                'verbose_name_plural': 'Group Usage Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserUsageSummary',
            fields=[
            ],
            options={
                'verbose_name': 'User Usage Summary',
                'verbose_name_plural': 'User Usage Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('entrypoint', models.CharField(max_length=64, null=True)),
                ('starttime', models.DateTimeField(blank=True, default=delft3dworker.utils.tz_now)),
                ('stoptime', models.DateTimeField(blank=True, null=True)),
                ('yaml', models.FileField(default='', upload_to='workflows/')),
                ('task_uuid', models.UUIDField(blank=True, default=None, null=True)),
                ('task_starttime', models.DateTimeField(blank=True, default=delft3dworker.utils.tz_now)),
                ('desired_state', models.CharField(choices=[('non-existent', 'Non-existent'), ('pending', 'Pending'), ('unknown', 'Unknown'), ('running', 'Running'), ('paused', 'Running (Suspended)'), ('succeeded', 'Succeeded'), ('skipped', 'Skipped'), ('failed', 'Failed'), ('error', 'Error')], default='non-existent', max_length=16)),
                ('cluster_state', models.CharField(choices=[('non-existent', 'Non-existent'), ('pending', 'Pending'), ('unknown', 'Unknown'), ('running', 'Running'), ('paused', 'Running (Suspended)'), ('succeeded', 'Succeeded'), ('skipped', 'Skipped'), ('failed', 'Failed'), ('error', 'Error')], default='non-existent', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('cluster_log', models.TextField(blank=True, default='')),
                ('action_log', models.TextField(blank=True, default='')),
                ('scene', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='delft3dworker.scene')),
                ('version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delft3dworker.version_docker')),
            ],
        ),
        migrations.AddField(
            model_name='scenario',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delft3dworker.template'),
        ),
    ]
