# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Delft3DWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(editable=False, max_length=256)),
                ('workerid', models.CharField(editable=False, max_length=256)),
                ('workingdir', models.CharField(editable=False, max_length=256)),
                ('fileurl', models.CharField(editable=False, max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=256)),
                ('info', models.CharField(max_length=256)),
                ('json', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workingdir', models.CharField(max_length=256)),
                ('fileurl', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('info', models.CharField(max_length=256)),
                ('json', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='PostprocessingTask',
            fields=[
                ('celerytask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delft3dworker.CeleryTask')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delft3dworker.Scene')),
            ],
            bases=('delft3dworker.celerytask',),
        ),
        migrations.CreateModel(
            name='ProcessingTask',
            fields=[
                ('celerytask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delft3dworker.CeleryTask')),
                ('scene', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='delft3dworker.Scene')),
            ],
            bases=('delft3dworker.celerytask',),
        ),
        migrations.CreateModel(
            name='SimulationTask',
            fields=[
                ('celerytask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delft3dworker.CeleryTask')),
                ('scene', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='delft3dworker.Scene')),
            ],
            bases=('delft3dworker.celerytask',),
        ),
    ]
