# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 10:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delft3dworker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='parameters',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='scenes_parameters',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='scene',
            name='parameters',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='searchform',
            name='sections',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=b'[]'),
        ),
        migrations.AlterField(
            model_name='searchform',
            name='templates',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=b'[]'),
        ),
        migrations.AlterField(
            model_name='template',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='sections',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='version_svn',
            name='versions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=b'{}'),
        ),
    ]
