# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 13:30
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delft3dworker', '0006_auto_20160202_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='delft3dworker',
            name='workerid',
            field=models.CharField(default=0, editable=False, max_length=256),
            preserve_default=False,
        ),
    ]
