# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 10:47
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delft3dworker', '0007_delft3dworker_workerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='delft3dworker',
            name='info',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
