# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delft3dworker', '0010_simrun_task_taskproc_tasksim_taskvis'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPostProcessing',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delft3dworker.Task')),
            ],
            bases=('delft3dworker.task',),
        ),
        migrations.CreateModel(
            name='TaskSimulation',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delft3dworker.Task')),
            ],
            bases=('delft3dworker.task',),
        ),
        migrations.RenameModel(
            old_name='SimRun',
            new_name='SimulationRun',
        ),
        migrations.RenameModel(
            old_name='TaskSim',
            new_name='TaskProcessing',
        ),
        migrations.RemoveField(
            model_name='taskproc',
            name='run',
        ),
        migrations.RemoveField(
            model_name='taskproc',
            name='task_ptr',
        ),
        migrations.RemoveField(
            model_name='taskvis',
            name='run',
        ),
        migrations.RemoveField(
            model_name='taskvis',
            name='task_ptr',
        ),
        migrations.RenameField(
            model_name='taskprocessing',
            old_name='run',
            new_name='simulationrun',
        ),
        migrations.DeleteModel(
            name='TaskProc',
        ),
        migrations.DeleteModel(
            name='TaskVis',
        ),
        migrations.AddField(
            model_name='tasksimulation',
            name='simulationrun',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='delft3dworker.SimulationRun'),
        ),
        migrations.AddField(
            model_name='taskpostprocessing',
            name='simulationrun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delft3dworker.SimulationRun'),
        ),
    ]
