# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delft3dworker', '0011_auto_20160309_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulationrun',
            name='workerid',
        ),
    ]
