# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delft3dworker', '0012_remove_simulationrun_workerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='taskpostprocessing',
            name='simulationrun',
        ),
        migrations.RemoveField(
            model_name='taskpostprocessing',
            name='task_ptr',
        ),
        migrations.RemoveField(
            model_name='taskprocessing',
            name='simulationrun',
        ),
        migrations.RemoveField(
            model_name='taskprocessing',
            name='task_ptr',
        ),
        migrations.RemoveField(
            model_name='tasksimulation',
            name='simulationrun',
        ),
        migrations.RemoveField(
            model_name='tasksimulation',
            name='task_ptr',
        ),
        migrations.AlterField(
            model_name='simulationrun',
            name='fileurl',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='simulationrun',
            name='workingdir',
            field=models.CharField(max_length=256),
        ),
        migrations.CreateModel(
            name='PostprocessingTask',
            fields=[
                ('celerytask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delft3dworker.CeleryTask')),
                ('simulationrun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delft3dworker.SimulationRun')),
            ],
            bases=('delft3dworker.celerytask',),
        ),
        migrations.CreateModel(
            name='ProcessingTask',
            fields=[
                ('celerytask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delft3dworker.CeleryTask')),
                ('simulationrun', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='delft3dworker.SimulationRun')),
            ],
            bases=('delft3dworker.celerytask',),
        ),
        migrations.CreateModel(
            name='SimulationTask',
            fields=[
                ('celerytask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delft3dworker.CeleryTask')),
                ('simulationrun', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='delft3dworker.SimulationRun')),
            ],
            bases=('delft3dworker.celerytask',),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskPostProcessing',
        ),
        migrations.DeleteModel(
            name='TaskProcessing',
        ),
        migrations.DeleteModel(
            name='TaskSimulation',
        ),
    ]
