# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delft3dworker', '0013_auto_20160309_1237'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SimulationRun',
            new_name='Scene',
        ),
        migrations.RenameField(
            model_name='postprocessingtask',
            old_name='simulationrun',
            new_name='Scene',
        ),
        migrations.RenameField(
            model_name='processingtask',
            old_name='simulationrun',
            new_name='Scene',
        ),
        migrations.RenameField(
            model_name='simulationtask',
            old_name='simulationrun',
            new_name='Scene',
        ),
    ]
