# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delft3dworker', '0015_auto_20160309_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scene',
            old_name='status',
            new_name='state',
        ),
    ]
