# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delft3dworker', '0017_remove_celerytask_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postprocessingtask',
            old_name='Scene',
            new_name='scene',
        ),
        migrations.RenameField(
            model_name='processingtask',
            old_name='Scene',
            new_name='scene',
        ),
        migrations.RenameField(
            model_name='simulationtask',
            old_name='Scene',
            new_name='scene',
        ),
    ]
