# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 18:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delft3dworker', '0023_auto_20160531_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='parameters',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='scenes_parameters',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='parameters',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='sections',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
