# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 18:10
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('delft3dworker', '0024_auto_20160530_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='parameters',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='scenes_parameters',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='scene',
            name='info',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='scene',
            name='parameters',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='template',
            name='meta',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='template',
            name='sections',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
    ]
