# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-29 09:42
from __future__ import unicode_literals

from __future__ import absolute_import
import delft3dworker.utils
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delft3dworker', '0087_auto_20180214_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('starttime', models.DateTimeField(blank=True, default=delft3dworker.utils.tz_now)),
                ('task_uuid', models.UUIDField(blank=True, default=None, null=True)),
                ('task_starttime', models.DateTimeField(blank=True, default=delft3dworker.utils.tz_now)),
                ('desired_state', models.CharField(choices=[(b'non-existent', b'Non-existent'), (b'pending', b'Pending'), (b'unknown', b'Unknown'), (b'running', b'Running'), (b'paused', b'Running (Suspended)'), (b'succeeded', b'Succeeded'), (b'skipped', b'Skipped'), (b'failed', b'Failed'), (b'error', b'Error')], default=b'non-existent', max_length=16)),
                ('cluster_state', models.CharField(choices=[(b'non-existent', b'Non-existent'), (b'pending', b'Pending'), (b'unknown', b'Unknown'), (b'running', b'Running'), (b'paused', b'Running (Suspended)'), (b'succeeded', b'Succeeded'), (b'skipped', b'Skipped'), (b'failed', b'Failed'), (b'error', b'Error')], default=b'non-existent', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='scene',
            name='workflow',
        ),
        migrations.AddField(
            model_name='scene',
            name='entrypoint',
            field=models.PositiveSmallIntegerField(choices=[(0, b'main workflow')], default=0),
        ),
        migrations.AddField(
            model_name='template',
            name='export_options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AddField(
            model_name='template',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={b'channel_network_images': {b'images': [], b'location': b'process/'}, b'delta_fringe_images': {b'images': [], b'location': b'process/'}, b'logfile': {b'file': '', b'location': b'simulation/'}, b'postprocess_output': {}, b'procruns': 0, b'sediment_fraction_images': {b'images': [], b'location': b'process/'}, b'subenvironment_images': {b'images': [], b'location': b'postprocess/'}}),
        ),
        migrations.AddField(
            model_name='template',
            name='visualisation',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AddField(
            model_name='template',
            name='yaml_template',
            field=models.FileField(default='', upload_to=b'workflows/'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='phase',
            field=models.PositiveSmallIntegerField(choices=[(0, b'New'), (6, b'Idle: waiting for user input'), (11, b'Starting workflow'), (12, b'Running workflow'), (13, b'Removing workflow'), (500, b'Finished')], default=0),
        ),
        migrations.AddField(
            model_name='workflow',
            name='scene',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='delft3dworker.Scene'),
        ),
    ]
