# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-30 08:32
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delft3dworker', '0089_template_shortname'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='action_log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workflow',
            name='cluster_log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workflow',
            name='yaml',
            field=models.FileField(default='', upload_to=b'workflows/'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='phase',
            field=models.PositiveSmallIntegerField(choices=[(0, b'New'), (6, b'Idle: waiting for user input'), (11, b'Starting workflow'), (12, b'Running workflow'), (13, b'Removing workflow'), (500, b'Finished'), (501, b'Failed')], default=0),
        ),
        migrations.AlterField(
            model_name='template',
            name='shortname',
            field=models.CharField(default=b'gt', max_length=256),
        ),
        migrations.AlterField(
            model_name='template',
            name='yaml_template',
            field=models.FileField(default='', upload_to=b'workflow_templates/'),
        ),
    ]
