# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 15:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delft3dworker', '0093_auto_20181112_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version_Docker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.CharField(db_index=True, max_length=256)),
                ('revision', models.PositiveSmallIntegerField(db_index=True)),
                ('versions', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('changelog', models.CharField(max_length=256)),
                ('reviewed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-revision'],
                'verbose_name': 'Docker version',
                'verbose_name_plural': 'Docker versions',
            },
        ),
        migrations.RemoveField(
            model_name='scene',
            name='entrypoint',
        ),
        migrations.AddField(
            model_name='workflow',
            name='entrypoint',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='template',
            name='shortname',
            field=models.CharField(default={}, max_length=256),
        ),
        migrations.AddField(
            model_name='version_docker',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='delft3dworker.Template'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delft3dworker.Version_Docker'),
        ),
    ]
