# Generated by Django 2.0.10 on 2019-02-11 11:26

from django.db import migrations, models

import delft3dworker.models


class Migration(migrations.Migration):
    dependencies = [
        ("delft3dworker", "0096_auto_20181206_1234"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenario",
            name="parameters",
            field=delft3dworker.models.JSONFieldTransition(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="scenes_parameters",
            field=delft3dworker.models.JSONFieldTransition(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="scene",
            name="info",
            field=delft3dworker.models.JSONFieldTransition(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="scene",
            name="parameters",
            field=delft3dworker.models.JSONFieldTransition(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="searchform",
            name="sections",
            field=delft3dworker.models.JSONFieldTransition(default=list),
        ),
        migrations.AlterField(
            model_name="searchform",
            name="templates",
            field=delft3dworker.models.JSONFieldTransition(default=list),
        ),
        migrations.AlterField(
            model_name="template",
            name="export_options",
            field=delft3dworker.models.JSONFieldTransition(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="template",
            name="info",
            field=delft3dworker.models.JSONFieldTransition(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="template",
            name="meta",
            field=delft3dworker.models.JSONFieldTransition(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="template",
            name="sections",
            field=delft3dworker.models.JSONFieldTransition(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="template",
            name="shortname",
            field=models.CharField(default=dict, max_length=256),
        ),
        migrations.AlterField(
            model_name="template",
            name="visualisation",
            field=delft3dworker.models.JSONFieldTransition(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="version_docker",
            name="versions",
            field=delft3dworker.models.JSONFieldTransition(default=dict),
        ),
    ]
