# Generated by Django 2.0.13 on 2020-02-26 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delft3dworker', '0097_auto_20190211_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scenario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scene',
            options={},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={},
        ),
    ]
