# Generated by Django 3.2.4 on 2021-06-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delft3dworker', '0099_alter_scene_phase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scene',
            options={'permissions': [('restricted_view_scene', 'Can view scene without actions.')]},
        ),
    ]
