# Generated by Django 3.2.25 on 2024-06-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delft3dworker", "0102_add_extended_view_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="yaml_template",
            field=models.FileField(default="", upload_to="workflow_templates"),
        ),
    ]
